### PR TITLE
Set Ruby 2.4.1 to be the minimum allowed version.

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by ioquatix** [comment]
Is travis set up for this repo?

**Comment by ioquatix** [comment]
Okay, this PR seems good to me, and I tested locally using 2.4.1 and everything was fine. @cfis can you review/merge? Thanks :)

**Comment by cfis** [comment]
I haven't setup a Travis repo yet because from what I can tell Ubuntu only supports older versions of proj which would result in a *lot* of test failures. But if there is a way to test against Proj 6 then that would be great.

**Comment by ioquatix** [comment]
Okay, I will take a look.

**Pull request merged**
